### ISSUE TITLE
Tracking issue for various optimizations

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#45]
## Overview

I've made a number of optimizations locally on phonopy and want to start contributing things back upstream.  I am creating an issue here to help me keep track (since it is not possible for me to make Issues on my own fork).

Here's a laundry list of things I will be trying to contribute:

* [x] Fix O(n^3) behavior in `get_smallest_vectors`
  - **status:** PR merged: #46
* [x] Expose a `compute_permutation` function implemented in C.
  - **status:** PR merged: #47 
* [x] Use `compute_permutation` in `distribute_fc2`
  - **status:** PR merged: #48
  - Will make another PR to clean up an unnecessary helper function.
* [x] ~Only compute permutations for generators~
  - **status:** I have decided against this for now since there are more pressing concerns.

### Fix O(n^3) behavior in `get_smallest_vectors`

In the current version of `get_smallest_equivalent_vectors`, we:
- do the following for **all N positions:**
  - compute the cartesian position (in `supercell.get_positions()`)
  - obtain the position scaled by `reduced_bases`
  - round it into `-0.5 < x < 0.5`
- ...but then **only use TWO of the positions!**

This makes `get_smallest_vectors` scale with O(n^3) when it really should only scale with O(n^2).

### Expose a `compute_permutation` function implemented in C.

The code in _distribute_fc2 for locating atoms that overlap can be [factored out](https://github.com/ExpHP/phonopy/blob/eigenvector-hack/c/_phonopy.c#L590-L688) and [optimized](https://github.com/ExpHP/phonopy/blob/eigenvector-hack/phonopy/harmonic/force_constants.py#L674-L710) to perform O(n log n) work instead of the O(n^2) overlap checks it currently does.  This same function can then also be used to implement `get_positions_sent_by_rot_inv`.  Two birds with one stone!

I've done this on my own local branches and the speedup on large structures is *phenomenal* (bringing `get_positions_sent_by_rot_inv` from 55 seconds down to 0.13 seconds).  However, this was a long time ago; I need to update it to incorporate your recent improvements (`distribute_fc2_all`).

### Only compute permutations for generators

To state the obvious, there is a group homomorphism between space group operators and permutations. 
 Therefore, to compute permutations for all space group operations, we can simply compute the generators and then compose them to find the rest.

**This might not be necessary;** `compute_permutation` is already pretty fast on the structures that I'm testing it on; however, I still need to benchmark it on a big structure that has screw and glide operations, which is where I think this optimization will become useful/necessary.
